# Generated by Django 6.0.2 on 2026-03-11 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0002_remove_member_password_member_role_member_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='division',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student_management_system.member'),
        ),
        migrations.AddField(
            model_name='member',
            name='teacher_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
