# Generated by Django 6.0.2 on 2026-03-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0003_member_division_member_student_id_member_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='can_add_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='can_delete_student',
            field=models.BooleanField(default=False),
        ),
    ]
