# Generated by Django 6.0.2 on 2026-03-13 06:14

import django.db.models.deletion
from django.db import migrations, models

def create_default_school(apps, schema_editor):
    School = apps.get_model("student_management_system", "School")
    if not School.objects.filter(id=1).exists():
        School.objects.create(id=1, name="Default School", code="default-school")


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_system', '0004_member_can_add_student_member_can_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.SlugField(unique=True)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(create_default_school),
        migrations.AddField(
            model_name='member',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='student_management_system.school'),
            preserve_default=False,
        ),
    ]
